# Generated by Django 4.0.6 on 2024-01-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('pwd', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
