# Generated by Django 4.0.6 on 2024-01-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('condition', models.CharField(max_length=40)),
                ('imgname', models.CharField(max_length=40)),
                ('regday', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
