# Generated by Django 4.0.6 on 2024-01-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_crop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crop',
            table='crop',
        ),
    ]
